---

- name: McAfee VSCL | Create temporary work dir
  file:
    path: "{{ mcafee_temp_dir }}/"
    state: directory

- name: McAfee VSCL | Download Package
  get_url:
    url: "{{ mcafee_vscl_tgz_url }}"
    dest: "{{ mcafee_temp_dir }}/vscl.tar.gz"
    validate_certs: yes

- file: path=/usr/local/uvscan state=directory

- name: McAfee VSCL | Extract files
  unarchive:
    src: "{{ mcafee_temp_dir }}/vscl.tar.gz"
    dest: /usr/local/uvscan
    remote_src: yes

- file: path=/usr/local/uvscan/uvscan mode="655"

- name: McAfee VSCL | Remove temporary work dir
  file:
    path: "{{ mcafee_temp_dir}}/"
    state: absent