---
- name: Set default value for variable generate_pki
  set_fact:
    generate_pki: True

- name: Set variable generate_pki
  set_fact:
    generate_pki: False
  when: not (frontend_openssl or rabbitmq_ssl or postgresql_ssl) or (root_external and pki_rabbitmq_external and pki_https_external and pki_psql_external)

- name: Check if infra name has been provided by user
  fail: msg="Please add '-e infra_name=<my_infra_name>' to the command-line to be able to run this playbook"
  when: generate_pki and infra_name == ""

- name: Check if infra data file exists
  stat:
    path: "{{ infra_data_file }}"
  register: infra_data_file_stat
  when: generate_pki

# If infra is brand new
- name: Create new infra
  include: create_infra.yml
  when: generate_pki and not infra_data_file_stat.stat.exists

# Update infra
- name: Update infra
  include: update.yml
  when: (frontend_openssl and not pki_https_external) or (postgresql_ssl and not pki_psql_external)
