---

# VirusTotal module configuration
virustotal_configs:
  - section: VirusTotal
    option: private
    value: False
  - section: VirusTotal
    option: apikey
    value: 1fe0ef5feca2f84eb450bc3617f839e317b2a686af4d651a9bada77a522201b0
