---

- name: Enable reboot on kernel panic on Linux hosts
  sysctl:
    name: "kernel.panic"
    value: 5
    sysctl_set: yes
    state: present
    reload: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- include: debian_install_packages.yml
  when: ansible_distribution == 'Debian'

- include: hosts.yml
- include: users_groups.yml

- include: locales.yml
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Create IRMA data directories
  file:
    path: "{{ item }}"
    owner: "{{ irma_user }}"
    group: "{{ irma_group }}"
    mode: 0755
    state: directory
  become: yes
  with_items:
    - /var/log/irma
    - /var/irma

- name: Create IRMA application directories
  file:
    path: "{{ item }}"
    owner: "{{ irma_user }}"
    group: "{{ irma_server_group }}"
    mode: 0750
    state: directory
  become: yes
  with_items:
    - /opt/irma

- name: Create IRMA certs directories
  file:
    path: "{{ item }}"
    owner: "{{ irma_user }}"
    group: "{{ irma_server_group }}"
    mode: 0750
    state: directory
  become: yes
  with_items:
    - "{{ dst_pki_folder }}"
