language: python
python:
  - "2.7"

install:
  - pip install pep8
  - pip install -r requirements.txt

before_script:
  - pep8 --version
  - sudo mkdir -p /var/log/irma/ && sudo touch /var/log/irma/sqlalchemy.log && sudo chmod 666 /var/log/irma/sqlalchemy.log
  # - export IRMA_BRAIN_CFG_PATH=tests/ && PYTHONPATH=. python scripts/create_user.py  test_brain test_brain test_brain

script:
  - pep8 brain config extras scripts tests
  - make testc

notifications:
  email:
    on_success: never
