---

- name: TrID | Check if present
  command: "{{ trid_install_dir }}/trid -?"
  failed_when: trid_present.rc != 1 # rc when printing --help
  register: trid_present
  ignore_errors: yes

- include: install.yml
  when: trid_present.failed
