---

  # This is needed because NodeSource repositories are using TLS
- apt:
    name: "apt-transport-https"
    state: present

- name: Add NodeJS apt Key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Add NodeJS Debian
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_major_version }}.x {{ ansible_distribution_release }} main"
    state: present
    filename: "nodesource"
    update_cache: yes

  # NodeJS nodesource repo add suffix to the package version (ie
  # `-1nodesource1`).
  # A wildcard is added to match the version with the one available in the
  # repo.
- apt:
    name: "nodejs={{ nodejs_major_version | mandatory }}*"
    state: present
