---

env:
  es6: true

parserOptions:
  ecmaVersion: 2018

extends: airbnb-base

globals:
  _: true
  angular: true
  moment: true

rules:
  # Allow https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y052
  no-use-before-define: 0
