---

- include: paths.yml

## Upload
- name: Remove file if existing
  win_file:
    path: "{{ remote_install_script }}"
    state: absent

- name: Uploading script
  win_copy:
    src: mcafee-installer.py
    dest: "{{ remote_install_script }}"

## Install
- name: Checking if already installed
  win_stat:
    path: '{{ mcafee_win_install_path }}/scan.exe'
  register: mcafee_win_vscl_installed

- name: Install McAfee VSCL
  raw: "py -3 {{ remote_install_script }} -v install -u {{ mcafee_win_url }} -p {{ mcafee_win_install_path }}"
  when: not mcafee_win_vscl_installed.stat.exists

## Clean
- name: Delete script
  win_file:
    path:  "{{ remote_install_script }}"
    state: "absent"
