---

- name: Pure-FTPD | Create group ftpgroup
  group:
    name=ftpgroup
    state=present

- name: Pure-FTPD | Add ftpuser to group ftpgroup
  user:
    name=ftpuser
    group=ftpgroup
    shell=/usr/sbin/nologin
    home=/dev/null

- name: Pure-FTPD | Link configuration for auth
  file:
    src=/etc/pure-ftpd/conf/PureDB
    dest=/etc/pure-ftpd/auth/50puredb
    state=link
    owner=root
    group=root

- name: Pure-FTPD | Create SSL's private dir
  file:
    path=/etc/ssl/private
    state=directory
    owner=root
    group=root
    mode=0700

- name: Pure-FTPD | Generate certificate
  command: openssl req -x509 -nodes -days 7300 -subj "{{ brain_pureftpd_openssl_subj }}" -newkey rsa:2048 -keyout /etc/ssl/private/pure-ftpd.pem -out /etc/ssl/private/pure-ftpd.pem
  args:
    creates: /etc/ssl/private/pure-ftpd.pem

- name: Pure-FTPD | Fix permissions on key file
  file:
    path=/etc/ssl/private/pure-ftpd.pem
    state=file
    owner=root
    group=root
    mode=0600

- name: Pure-FTPD | Lookup created virtual users
  command: pure-pw show {{ item.username }}
  with_items: brain_pureftpd_virtual_users
  register: pure_ftpd_users_status
  ignore_errors: True

- name: Pure-FTPD | Add virtual users
  template:
    src=pure-ftpd.pwd
    dest=/tmp/{{ item.item.username }}.pwd
    owner=root
    group=root
    mode=0600
  when: item.rc != 0
  with_items: "{{ pure_ftpd_users_status.results }}"
  register: pure_ftpd_users

- shell: pure-pw useradd {{ item.username }} -u {{ item.virtual_user }} -d {{ item.virtual_home }} -m < /tmp/{{ item.username }}.pwd
  with_items: "{{ brain_pureftpd_virtual_users }}"
  when: pure_ftpd_users | changed

- name: Pure-FTPD | Update user database
  command: pure-pw mkdb
  when: pure_ftpd_users | changed
  notify: Restart Pure-FTPD daemon
