---

## Global
probe_user: "{{ default_user }}"
probe_group: "{{ default_group }}"

irma_install_dir_linux: /opt/irma
irma_install_dir_windows: C:/IRMA
irma_install_dir: "{{ irma_install_dir_linux if 'Windows' not in ansible_distribution else irma_install_dir_windows }}"

probe_project_dir: "{{ irma_install_dir }}/irma-probe"
probe_install_dir: "{{ probe_project_dir }}/current"
probe_venv_dir: "{{ probe_install_dir }}/venv"


## Deployment
probe_deployment_configs:
  - section: broker_probe
    option: host
    value: "{{ brain_addr }}"
  - section: broker_probe
    option: port
    value: "{{ rabbitmq_configuration.port  }}"
  - section: broker_probe
    option: vhost
    value: "{{ rabbitmq_configuration.probe.vhost }}"
  - section: broker_probe
    option: username
    value: "{{ rabbitmq_configuration.probe.user }}"
  - section: broker_probe
    option: password
    value: "{{ rabbitmq_configuration.probe.password }}"
  - section: broker_brain
    option: host
    value: "{{ brain_addr }}"
  - section: broker_brain
    option: port
    value: "{{ rabbitmq_configuration.port }}"
  - section: broker_brain
    option: vhost
    value: "{{ rabbitmq_configuration.brain.vhost }}"
  - section: broker_brain
    option: username
    value: "{{ rabbitmq_configuration.brain.user }}"
  - section: broker_brain
    option: password
    value: "{{ rabbitmq_configuration.brain.password }}"
  - section: ftp_brain
    option: host
    value: "{{ brain_addr }}"
  - section: ftp_brain
    option: username
    value: "{{ ftpd_configuration.probe.username }}"
  - section: ftp_brain
    option: password
    value: "{{ ftpd_configuration.probe.password }}"
  - section: ssl_config
    option: activate_ssl
    value: "{{ rabbitmq_ssl }}"
  - section: ssl_config
    option: ca_certs
    value: "{{ dst_pki_folder }}/rabbitmq-ca.crt"
  - section: ssl_config
    option: keyfile
    value: "{{ dst_pki_folder }}/probe-client.key"
  - section: ssl_config
    option: certfile
    value: "{{ dst_pki_folder }}/probe-client.crt"
  - section: probes_config
    option: unarchive_max_size
    value: 5Go
  - section: probes_config
    option: unarchive_max_file_size
    value: 50Mo
  - section: probes_config
    option: unarchive_max_files
    value: 300
## Systemd role
systemd_units_probe:
  - name: "{{ irma_unit_prefix }}probe_app.service"
    Service:
      ExecStart: "{{ probe_venv_dir }}/bin/python -m probe.tasks"
      WorkingDirectory: "{{ probe_install_dir }}"
      SyslogIdentifier: "{{ syslog_identifiers.probe.name }}"

# VirusTotal module configuration
# Uncomment this to share an apikey to all virustotal probes

virustotal_private_apikey: False
virustotal_apikey: 88eb8e2f869e98ea9b0367cb47c143cb438a5e8d8dfd3b6e3fb6c898374b8fb6

virustotal_configs:
  - section: VirusTotal
    option: private
    value: "{{ virustotal_private_apikey }}"
  - section: VirusTotal
    option: apikey
    value: "{{ virustotal_apikey }}"

# Bit Defender Scanner key - Put your licence key here
# bitdefender_scanner_key:

# Zoner Antivirus - put you licence key here
# zoner_license_key: XXXXX-XXXXX-XXXXX-XXXXX-XXXXX

# DrWeb Antivirus - put your configurations there
# drweb_configs:
#   - section: LinuxSpider
#     option: Start
#     value: No
# drweb_license_key: XXXX-XXXX-XXXX-XXXX

# Avast! licence file - Put your licence file here
# avast_license_file: files/license.avastlic

# Sophos Antivirus Antivirus for Linux (Free) - Put your variables here
# sophos_archive_name: sav-linux-free-9.9.tgz
# sophos_update_username: ABCDEFGH
# sophos_update_password: 01s21z54ee

#Kaspersky license file - Put your license file here
# kaspersky_license_file: files/license.key

#eset_file_security_user:
#eset_file_security_pwd:
#eset_file_security_licence_file:
