---

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"

- include_tasks: debian.yml
  when: ansible_distribution in ['Debian', 'Ubuntu']

- include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
