---

- name: F-Secure | Create temporary work dir
  file:
    path: "{{ fsecure_temp_dir }}/"
    state: directory

- name: F-Secure | Download latest definition files
  get_url:
    url: "{{ fsecure_signatures_url }}"
    dest: "{{ fsecure_temp_dir }}/fsdbupdate9.run"
  retries: 5
  delay: 30

- name: F-Secure | Apply latest definition files
  command: /usr/bin/dbupdate "{{ fsecure_temp_dir }}/fsdbupdate9.run"
  register: command_result
  # https://help.f-secure.com/product.html?business/igk/5.30/en/topic_9058AA384A0E45A192CEBD211B763FA6-5.30-en
  # rc = 0 means no update rc = 2 means updated
  failed_when: "{{ command_result.rc  }} == 1"
  become: yes

- name: F-Secure | Remove temporary work dir
  file:
    path: "{{ fsecure_temp_dir }}/"
    state: absent
