---

- name: ComodoCAVL | Install dependencies
  apt:
    name: ['binutils', 'libqt4-sql', 'libqt4-network', 'libqtgui4']
    state: present

- name: ComodoCAVL | Create temporary work dir
  file:
    path: "{{ comodo_cavl_temp_dir }}"
    state: directory

- name: ComodoCAVL | Download Package
  get_url:
    url: "{{ comodo_cavl_deb_url }}"
    dest: "{{ comodo_cavl_temp_dir }}/comodo.deb"
  when: ansible_os_family == "Debian"

- name: ComodoCAVL | Extract files
  shell: ar x "{{ comodo_cavl_temp_dir }}/comodo.deb"
  args:
    chdir: "{{ comodo_cavl_temp_dir }}"
    creates: "{{ comodo_cavl_temp_dir }}/data.tar.gz"

- name: ComodoCAVL | Install files
  unarchive:
    src: "{{ comodo_cavl_temp_dir }}/data.tar.gz"
    dest: "/"
    remote_src: yes

- name: ComodoCAVL | Remove temporary work dir
  file:
    path: "{{ comodo_cavl_temp_dir }}"
    state: absent
