---

- name: add a fancy message to the box
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0750

- name: Install common needed packages for IRMA
  apt:
    name: ['postgresql-server-dev-9.6', 'uwsgi-plugin-python3',
          'python3-psycopg2']
    state: present

- name: Ensure good rights on IRMA-Frontend install directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ frontend_user }}"
    group: "{{ irma_server_group }}"
    mode: "u=rwX,g=rX,o="
    recurse: yes
  with_items:
    - "{{ frontend_project_dir }}"
    - "{{ common_project_dir }}"

- name: Ensure that www-data can access IRMA files and certificates
  user:
    name: www-data
    groups: "{{ irma_server_group }},{{ irma_cert_group }}"
    append: yes

- include: openssl_configuration.yml
  when: frontend_openssl|default(False) == True

  # See https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
- include: puppeteer_requirements.yml
  when: irma_environment != 'production'

# vim: sw=2
