---

- name: Sophos | Check installed version
  command: /opt/sophos-av/bin/savscan --version
  ignore_errors: yes
  register: sophos_present

- name: Sophos | Installation already done
  debug:
    msg: "Sophos is already installed. Skipping the installation part..."
  when: sophos_present is success

- name: Sophos | Installation can not proceed
  debug:
    msg: "Sophos won't be installed because you have not provided an archive name ('sophos_archive_name' variable)."
  when: (sophos_present is failed) and not sophos_archive_name

- include: install.yml
  when: (sophos_present is failed) and sophos_archive_name
