---

- fail:
    msg: Update key not set. Please register at http://www.zonerantivirus.com/ to get an activation key. Fill your update key in host_vars or group_vars
  when: zoner_license_key is not defined

- name: Zoner | Check version
  command: zavcli --version
  ignore_errors: yes
  register: zoner_present

- include: install.yml
  when: zoner_present is failed
