---

- name: Configure additional UFW rules
  ufw:
    port: "{{ item.port if item.port is defined else '' }}"
    rule: "{{ item.rule if item.rule is defined else 'allow' }}"
    proto: "{{ item.proto if item.proto is defined else 'any' }}"
    to_ip: "{{ item.to_ip if item.to_ip is defined else 'any' }}"
    from_ip: "{{ item.from_ip if item.from_ip is defined else 'any' }}"
  with_items: "{{ ufw_additional_rules }}"
  become: yes
  notify: Reload UFW
